<div class="tve-total-new-leads">
    <?php echo __('Showing', 'thrive-leads') ?>
    <strong><#= (currentPage-1)*itemsPerPage #></strong>
    <?php echo __('to', 'thrive-leads') ?>
    <strong><#= currentPage * itemsPerPage > total_items ? total_items : currentPage * itemsPerPage #></strong>
    <?php echo __('from a total of', 'thrive-leads') ?>
    <strong><#= total_items #></strong>
    <?php echo __('records', 'thrive-leads') ?>
</div>

<div id="pages">
    <# if( pageCount > 1) { #>
        <a <# if(currentPage > 1) { #> href="#" class="page" value="1" <# } #>>&laquo; <?php echo __('First Page', 'thrive-leads'); ?></a>
        <a <# if(currentPage > 1) { #> href="#" class="page" value="<#= currentPage - 1 #>" <# } #>>< <?php echo __('Previous Page', 'thrive-leads'); ?></a>

        <# for(var i = currentPage - pagesToDisplay; i<= (currentPage + pagesToDisplay) && i<=pageCount; i++) { #>
            <# if(i>0) { #>
                <# if (i == currentPage) { #>
                    <b><#= i #></b>
                <# } else { #>
                    <a href="#" class="page" value="<#= i #>"><#=i#></a>
                <# } #>
            <# } #>
        <# } #>
        <a <# if(currentPage < pageCount) { #> href="#" class="page" value="<#= (currentPage + 1) #>" <# } #>><?php echo __('Next Page', 'thrive-leads'); ?> ></a>
        <a <# if(currentPage < pageCount) { #> href="#" class="page" value="<#= pageCount #>" <# } #>><?php echo __('Last Page', 'thrive-leads'); ?> &raquo;</a>
    <# } #>
</div>