<?php thrive_dashboard_display_messages(); ?>

<div class="tvedash-container">
    <div class="tvedash-header tvedash-header-connected">
        <img src="<?php echo thrive_dashboard_url(); ?>css/images/thrive-dash-logo.png">

        <div class="tvedash-pull-right">
            <div class="tvedash-clearfix">
                <img class="tvedash-pull-left" src="<?php echo thrive_dashboard_url(); ?>css/images/share-thrive.png">

                <div class="tvedash-pull-left">
                    <?php require "partial-share-links.php"; ?>
                </div>
            </div>
        </div>
    </div>

    <?php thrive_dashboard_display_messages(); ?>

    <h1 class="tvedash-separator-header">
        <?php _e('Currently Installed Products on this Site:'); ?>
    </h1>
    <?php if (count($products)) : ?>
        <ul class="tvedash-list-grid-4 tvedash-clearfix">
            <?php foreach ($products as $product) : ?>
                <li>
                    <div class="tvedash-content-box">
                        <div class="tvedash-content-box-head">
                            <div class="tvedash-plugin-img">
                                <img src="<?php echo $product['image_url'] ?>">
                            </div>
                            <h2><?php echo $product['name'] ?></h2>
                        </div>
                        <div class="tvedash-content-box-body">
                            <div class="tvedash-plugin-desc">
                                <?php echo !empty($product['description']) ? $product['description'] : '' ?>
                            </div>
                        </div>
                        <div class="tvedash-content-box-footer">
                            <?php if (!empty($product['button'])): ?>
                                <a href="<?php echo $product['button']['url'] ?>" class="tvedash-btn tvedash-btn-default tvedash-btn-block"><?php echo $product['button']['caption'] ?></a>
                            <?php else: ?>
                                <a class="tvedash-btn tvedash-btn-default tvedash-btn-block tvedash-btn-disabled"><?php _e('No options available'); ?></a>
                            <?php endif; ?>
                            <ul class="tvedash-mini-menu tvedash-text-center">
                                <?php if (count($product['links'])) : ?>
                                    <ul>
                                        <?php foreach ($product['links'] as $product_link) : ?>
                                            <li>
                                                <a class="<?php echo !empty($product_link['css_class']) ? $product_link['css_class'] : '' ?>" href="<?php echo $product_link['url'] ?>">
                                                    <?php echo $product_link['caption'] ?>
                                                </a>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php endif; ?>
                            </ul>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>

    <h1 class="tvedash-separator-header">Thrive Plugins:</h1>

    <div id="thrive-offer" class="tvedash-collapsible tvedash-collapsible-closed">
        <div class="tvedash-collapsible-head">
            <?php _e('Get Instant Access to All Our Awesome Products!'); ?>
            <button class="toggle"></button>
        </div>
        <div class="tvedash-collapsible-body">
            <div class="tvedash-showcase">
                <div class="tvedash-showcase-left">
                    <ul class="tvedash-showcase-list">
                        <li>
                            <strong>Have access to all of our plugins and themes and any we release in the future</strong> (of which there will be many!)
                        </li>
                        <li>
                            <strong>Receive a <span class="important">$30 Discount</span> off the regular membership price</strong>
                        </li>
                        <li>
                            <strong>Lock yourself in at the lowest rate</strong> (this is the lowest price this offer will ever be. Prices will increase as our offer grows, but if you sign up today your rate will never change for as long as you remain a member)
                        </li>
                        <li>
                            <strong>Get unlimited access to our support forum - our dedicated team of WordPress experts can help
                                solve any issues that you have</strong>
                        </li>
                    </ul>
                </div>
                <div class="tvedash-showcase-right">
                    <div class="tvedash-text-center tvedash-showcase-image">
                        <img src="<?php echo thrive_dashboard_url(); ?>css/images/themes-ad.png">
                    </div>
                </div>
                <div class="tvedash-text-center">
                    <button class="tvedash-btn tvedash-btn-success">Get Instant Access with the $30 Discount</button>
                </div>
            </div>

            <iframe style="width: 100%; height: 300px;" src="<?php echo THRIVE_DASHBOARD_OFFER_IFRAME_URL ?>"></iframe>
        </div>
    </div>

    <ul class="tvedash-list-grid-4 tvedash-clearfix">
        <?php foreach ($other_products as $product): ?>
            <li>
                <div class="tvedash-content-box">
                    <div class="tvedash-content-box-head">
                        <div class="tvedash-plugin-img">
                            <img src="<?php echo $product->image_url; ?>">
                        </div>
                        <h2><?php echo $product->name; ?></h2>
                    </div>
                    <div class="tvedash-content-box-body">
                        <div class="tvedash-plugin-desc">
                            <?php echo $product->description; ?>
                        </div>
                    </div>
                    <div class="tvedash-content-box-footer">
                        <a href="<?php echo THRIVE_DASHBOARD_DOWNLOAD_URL . $product->tag; ?>" class="tvedash-btn tvedash-btn-default tvedash-btn-block">
                            <?php _e('Learn More'); ?>
                        </a>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
    <h1 class="tvedash-separator-header thrive-themes-section">Thrive Themes:</h1>

    <div class="tvedash-alert tvedash-alert-danger error-change-theme" style="display: none;">
        <?php _e('An error occured while changing the theme.'); ?>
    </div>
    <ul class="tvedash-list-grid-4 tvedash-clearfix equal-heights">
        <?php foreach ($thrive_themes as $theme): ?>
            <li>
                <div class="tvedash-content-box <?php if ($theme->installed): ?>tvedash-content-box-active<?php endif; ?>">
                    <div class="tvedash-content-box-head">
                        <div class="tvedash-plugin-img">
                            <img src="<?php echo thrive_dashboard_url(); ?>css/images/theme-logo-<?php echo $theme->tag; ?>.png">
                        </div>
                    </div>
                    <div class="tvedash-content-box-footer tvedash-theme-<?php echo $theme->tag; ?>">
                        <?php if ($theme->installed): ?>
                            <button data-theme="<?php echo $theme->tag; ?>" class="tvedash-btn tvedash-btn-default tvedash-btn-block td-change-theme">
                                <?php _e('Activate'); ?>
                            </button>
                        <?php else: ?>
                            <a href="<?php echo THRIVE_DASHBOARD_DOWNLOAD_URL . $theme->tag; ?>" class="tvedash-btn tvedash-btn-default tvedash-btn-block">
                                <?php _e('Get this theme'); ?>
                            </a>
                        <?php endif; ?>

                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>

</div>