<div class="tvedash-container">
    <div class="tvedash-header">
        <img src="<?php echo thrive_dashboard_url(); ?>css/images/thrive-dash-logo.png">

        <div class="tvedash-pull-right">
            <div class="tvedash-clearfix">
                <img class="tvedash-pull-left" src="<?php echo thrive_dashboard_url(); ?>css/images/share-thrive.png">

                <div class="tvedash-pull-left">
                    <?php require "partial-share-links.php"; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="tvedash-panel">
        <div class="tvedash-panel-head">Integrations</div>
        <div class="tvedash-panel-body">
            <h2>These integrations are shared between all your Thrive products.</h2>
            <ul class="tvedash-list-grid-4 tvedash-clearfix">
                <?php foreach ($products as $product): ?>
                    <li>
                        <a href="<?php echo $product['url']; ?>">
                            <div class="tvedash-content-box tvedash-content-box-gray tvedash-content-box-border-3 tvedash-content-box-no-footer">
                                <div class="tvedash-content-box-head">
                                    <div class="tvedash-plugin-img">
                                        <img src="<?php echo $product['image_url']; ?>" alt="<?php echo $product['name']; ?>">
                                    </div>
                                    <h2><?php echo $product['name']; ?></h2>
                                </div>
                                <div class="tvedash-content-box-body">
                                    <?php echo $product['description']; ?>
                                </div>
                            </div>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>