<h1><?php echo __("License Manager"); ?></h1>

<?php thrive_dashboard_display_messages(); ?>

<!-- License manager -->
<div class="tvedash-container">
    <div class="tvedash-header">
        <img src="<?php echo thrive_dashboard_url(); ?>css/images/thrive-dash-logo.png">

        <div class="tvedash-pull-right">
            <div class="tvedash-clearfix">
                <img class="tvedash-pull-left" src="<?php echo thrive_dashboard_url(); ?>css/images/share-thrive.png">

                <div class="tvedash-pull-left">
                    <?php require "partial-share-links.php"; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="tvedash-panel">
        <div class="tvedash-panel-head"><?php _e('License Manager'); ?></div>
        <div class="tvedash-panel-body">
            <div class="tvedash-licenses tvedash-clearfix">
                <div class="tvedash-licenses-left">
                    <?php if (count($no_licensed_products)) : ?>
                        <h2><?php _e('Click on product to activate license'); ?></h2>
                        <ul class="tvedash-list-grid-3 tvedash-clearfix">
                            <?php foreach ($no_licensed_products as $key => $no_licensed) : ?>
                                <li>
                                    <div class="tvedash-content-box tvedash-content-box-collapsable tvedash-content-box-no-footer
                                    tvedash-content-box-<?php echo isset($_GET['selected']) && $_GET['selected'] == $no_licensed['tag'] ? 'open' : 'closed' ?>">
                                        <div class="tvedash-content-box-head">
                                            <div class="tvedash-plugin-img">
                                                <img src="<?php echo $no_licensed['image_url']; ?>"
                                                     alt="<?php echo $no_licensed['name']; ?>">
                                            </div>
                                            <div class="tvedash-plugin-title">
                                                <h2><?php echo $no_licensed['name']; ?></h2>
                                            </div>
                                        </div>
                                        <div class="tvedash-content-box-body">
                                            <form action="" method="POST">
                                                <input type="text" name="license_email"
                                                       placeholder="<?php echo __("Email Address") ?>"
                                                       value="<?php echo !empty($license_email) ? $license_email : '' ?>"/>

                                                <input type="text" name="license_key"
                                                       placeholder="<?php echo __("License Key") ?>"
                                                       value="<?php echo !empty($license_key) ? $license_key : '' ?>"/>

                                                <input type="hidden" name="product_tag"
                                                       value="<?php echo $no_licensed['tag']; ?>"/>

                                                <?php if(!empty($no_licensed['ids'])): ?>
                                                <?php foreach($no_licensed['ids'] as $no_licensed_id) : ?>
                                                    <input type="hidden" name="product_ids[]" value="<?php echo $no_licensed_id ?>" />
                                                <?php endforeach;?>
                                                <?php endif; ?>

                                                <button name="td_license" value="activate"
                                                        class="button button-primary button-large" type="submit">
                                                    <?php echo __("Activate License") ?>
                                                </button>

                                            </form>
                                        </div>
                                    </div>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php else: ?>
                        <h2><?php echo __("No product requiring activation.") ?></h2>
                    <?php endif; ?>
                </div>
                <div class="tvedash-licenses-right">
                    <h2><?php _e("Licenses already activated on this site"); ?></h2>

                    <div class="tvedash-content-box tvedash-content-box-green tvedash-content-box-no-footer">
                        <div class="tvedash-content-box-body tvedash-text-left">
                            <?php if (count($licensed_products)) : ?>
                                <ul class="tvedash-list">
                                    <?php foreach ($licensed_products as $licensed): ?>
                                        <li><span class="tvedash-icon-check-o"></span><?php echo $licensed['name'] ?>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            <?php else: ?>
                                <p><?php _e("No license activated.") ?></p>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>