<table>
    <thead>
    <tr>
        <th data-field-display="source" class="tve-tracking-field"><?php echo __('Campaign Source', 'thrive-leads'); ?></th>
        <th data-field-display="medium" class="tve-tracking-field"><?php echo __('Campaign Medium', 'thrive-leads'); ?></th>
        <th data-field-display="campaign" class="tve-tracking-field"><?php echo __('Campaign Name', 'thrive-leads'); ?></th>
        <th><?php echo __('Conversions', 'thrive-leads'); ?></th>
    </tr>
    </thead>
    <tbody id="tve-table-items"></tbody>
</table>