<p class="tve-form-description"><?php echo __('Give your 2 Step Lightbox a name. Usually your 2 Step Lightbox would be named after the promotion that you\'re running. For instance "Weight Loss Report"', 'thrive-leads') ?></p>

<div class="tve-form">
    <label class="form-label tve-control-label"><?php echo __('2 Step Lightbox Name', 'thrive-leads') ?></label>
    <div class="form-field">
        <input type="text" name="post_title" value="" class="post_title" tabindex="1">
    </div>
    <div class="form-buttons center">
        <a href="javascript:void(0)" class="tve-btn tve-btn-gray tve-btn-large tve-close-thickbox" tabindex="3"><?php echo __('Cancel', 'thrive-leads') ?></a>
        &nbsp;
        <a href="javascript:void(0)" class="tve-btn tve-btn-green tve-btn-large tve-add-lead-two-step-lightbox tl-enter-action" tabindex="2"><?php echo __('Add 2 Step Lightbox', 'thrive-leads') ?></a>
    </div>
</div>