<div class="tve-leads-files-step1">
    <p class="tve-form-description"><?php echo __('Give your Asset Group a name. Usually your asset group would be named after the promotion that you\'re running. For instance "Weight Loss Report"', 'thrive-leads') ?></p>

    <div class="tve-form">
        <label class="form-label tve-control-label"><?php echo __('Asset Group Name', 'thrive-leads') ?></label>

        <div class="form-field">
            <input type="text" name="post_title" value="" class="post_title" tabindex="1">
        </div>
        <div class="form-buttons center">

            <a tabindex="2" href="javascript:void(0)"
               class="tve-btn tve-btn-green tve-btn-large tve-add-asset-group tl-enter-action"><?php echo __('Save & Continue', 'thrive-leads') ?></a>
        </div>
    </div>
</div>
<div class="tve-leads-asset-files-manager" style="display: none;">
    <p class="tve-form-description larger-text"><?php echo __('Add one or more files that will be delivered to your new leads when they opt-in to receive this offer', 'thrive-leads') ?>
        .</p>

    <div class="tve-form">
        <div class="tve-form-wrapper">
            <ul class="tve-inside-collapsable-list tve-asset-group-container tve-table-condensed"
                id="tve-asset-group-files">
                <li class="asset-file-list-title tve-inside-collapsable-list-item clearfix">
                    <span class="asset-file-list-part tve-inside-collapsable-part"><?php echo __("Name", "thrive-cb") ?></span>
                    <span class="asset-file-list-part tve-inside-collapsable-part"><?php echo __("Link Anchor Text", "thrive-cb") ?></span>
                    <span class="asset-file-list-part tve-inside-collapsable-part"><?php echo __("File URL", "thrive-cb") ?></span>
                    <span class="asset-file-list-part tve-group-title tve-inside-collapsable-part-last">&nbsp;</span>
                </li>
                <li class="asset-file-list-no-files clearfix">
                    <span class="asset-file-list-part"><?php echo __("No Files Yet", "thrive-cb") ?></span>
                </li>
            </ul>
            <button
                class="tve-btn tve-btn-green  tve-leads-asset-media"><?php echo __("Add New File", "thrive-cb") ?></button>
        </div>
        <div class="form-buttons center">
            <a href="javascript:void(0)" class="tve-btn tve-btn-gray tve-btn-large tve-close-thickbox"
               tabindex="3"><?php echo __('Cancel', 'thrive-leads') ?></a>
            &nbsp;
            <a tabindex="2" href="javascript:void(0)"
               class="tve-btn tve-btn-green tve-btn-large tve-asset-save-group tl-enter-action"><?php echo __('Save & Continue', 'thrive-leads') ?></a>
        </div>
    </div>
</div>
