<div class="tve-form">
    <p>&nbsp;</p>
    <label class="form-label tve-control-label"><?php echo __('Choose the File to Add', 'thrive-leads') ?></label>
    <div class="form-field">
        <select class="tve-asset-prev-select"></select>
    </div>
    <div class="form-buttons center">
        <a href="javascript:void(0)" class="tve-btn tve-btn-gray tve-btn-large tve-close-thickbox" tabindex="3"><?php echo __('Cancel', 'thrive-leads') ?></a>
        &nbsp;
        <a tabindex="2" href="javascript:void(0)" class="tve-btn tve-btn-green tve-btn-large tve-add-asset-file tl-enter-action"><?php echo __('Add File', 'thrive-leads') ?></a>
    </div>
</div>

