<h2><?php echo __('Are you sure you want to archive this Form?', 'thrive-leads') ?></h2>

<p class="tve-form-description"><?php echo __('This will move the form to the archive', 'thrive-leads') ?></p>

<div class="tve-form">
    <div class="form-buttons center">
        <a href="javascript:void(0)" class="tve-btn tve-btn-gray tve-btn-large tve-close-thickbox"><?php echo __('Cancel', 'thrive-leads') ?></a>
        &nbsp; &nbsp;
        <a href="javascript:void(0)" class="tve-btn tve-btn-red tve-btn-large tve-confirm"><?php echo __('Move to Archive', 'thrive-leads') ?></a>
    </div>
</div>