<h2><?php echo __('Warning: You are about to delete Form: ', 'thrive-leads') ?> &laquo; <em><#= post_title #></em> &raquo; </h2>

<p class="tve-form-description"><?php echo __('You will lose the design and all conversion data associated with this form. This can\'t be undone. ', 'thrive-leads') ?></p>

<div class="tve-form">
    <div class="form-buttons center">
        <a href="javascript:void(0)" class="tve-btn tve-btn-gray tve-btn-large tve-close-thickbox"><?php echo __('Cancel', 'thrive-leads') ?></a>
        &nbsp; &nbsp;
        <a href="javascript:void(0)" class="tve-btn tve-btn-red tve-btn-large tve-confirm-delete-form"><?php echo __('Delete Form', 'thrive-leads') ?></a>
    </div>
</div>