<h2><?php echo __('Warning: You are about to delete the archive logs', 'thrive-leads') ?> </h2>

<p class="tve-form-description"><?php echo __('This will also delete your archived tests, archived tests history, and the data (impressions / conversions) recorded for your archived forms. These changes cannot be reversed.', 'thrive-leads') ?></p>

<div class="tve-form">
    <div class="form-buttons center">
        <a href="javascript:void(0)" class="tve-btn tve-btn-gray tve-btn-large tve-close-thickbox"><?php echo __('Cancel', 'thrive-leads') ?></a>
        &nbsp; &nbsp;
        <a href="javascript:void(0)" class="tve-btn tve-btn-red tve-btn-large tve-confirm-delete-archives"><?php echo __('Delete Logs', 'thrive-leads') ?></a>
    </div>
</div>