<h2><?php echo __('Warning! You are about to delete 2 Step Lightbox', 'thrive-leads') ?> <em><#= post_title #></em> !</h2>

<p class="tve-form-description"><?php echo __('This will delete all forms and statistics and cannot be reversed', 'thrive-leads') ?></p>

<div class="tve-form">
    <div class="form-buttons center">
        <a href="javascript:void(0)" class="tve-btn tve-btn-gray tve-btn-large tve-close-thickbox"><?php echo __('Cancel', 'thrive-leads') ?></a>
        &nbsp; &nbsp;
        <a href="javascript:void(0)" class="tve-btn tve-btn-red tve-btn-large tve-confirm-delete-lead-group"><?php echo __('Delete 2 Step Lightbox', 'thrive-leads') ?></a>
    </div>
</div>