<h2 class="warning"><?php echo __('Warning! You are about to delete Asset Group', 'thrive-leads') ?> <em><#= name #></em>!</h2>

<p class="tve-form-description"><?php echo __('This will delete the file associacion in this Asset Group, and cannot be reversed', 'thrive-leads') ?></p>

<div class="tve-form">
    <div class="form-buttons center">
        <a href="javascript:void(0)" class="tve-btn tve-btn-gray tve-btn-large tve-close-thickbox"><?php echo __('Cancel', 'thrive-leads') ?></a>
        &nbsp; &nbsp;
        <a href="javascript:void(0)" class="tve-btn tve-btn-red tve-btn-large tve-confirm-delete-asset-file"><?php echo __('Delete Asset Group', 'thrive-leads') ?></a>
    </div>
</div>