<h2 class="warning"><?php echo __('Warning! You are about to reset all statistics for', 'thrive-leads') ?> <em><#= post_title #></em>!</h2>

<p class="tve-form-description">
    <?php echo __("This will delete all statistics (form impressions, conversions, conversion rates etc) that were recorded for this form. Do you want to continue?", 'thrive-leads') ?>
</p>

<div class="tve-form">
    <div class="form-buttons center">
        <a href="javascript:void(0)" class="tve-btn tve-btn-gray tve-btn-large tve-close-thickbox"><?php echo __('Cancel', 'thrive-leads') ?></a>
        &nbsp; &nbsp;
        <a href="javascript:void(0)" class="tve-btn tve-btn-red tve-btn-large tve-confirm-reset"><?php echo __('Reset stats', 'thrive-leads') ?></a>
    </div>
</div>