<span class="asset-file-list-part tve-inside-collapsable-part">
    <span class="tve-icon-file-empty"></span>
    <span class="asset-group-file-title asset-group-file"><#= name #></span>
    <input class="tve-form-control tve-input-small tve-input-inline tve-input-condensed tve-edit-file-name-input tve-edit-file-name-title-input" style="display: none;">
    <a href="javascript:void(0)" class="tve-btn tve-btn-icon tve-edit-file-name tve-edit-file-name-title" style="margin-right: 5px;">
        <span class="tve-icon-pencil"></span>
    </a>
</span>
<span class="asset-file-list-part tve-inside-collapsable-part">
    <span class="asset-group-anchor-title asset-group-file"><#= link_anchor #></span>
    <input class="tve-form-control tve-input-small tve-input-inline tve-input-condensed tve-edit-file-name-input tve-edit-file-name-anchor-input" style="display: none;">
    <a href="javascript:void(0)" class="tve-btn tve-btn-icon tve-edit-file-name tve-edit-file-name-anchor" style="margin-right: 5px;">
        <span class="tve-icon-pencil"></span>
    </a>
</span>
<span class="asset-file-list-part tve-inside-collapsable-part"><a href="<#= link #>" target="_blank"><#= link #></a></span>
<span class="asset-file-list-part tve-inside-collapsable-part-last"><a href="javascript:void(0)" title="<?php echo __('Delete File', 'thrive-leads') ?>" data-title="<?php echo __('Delete File', 'thrive-leads') ?>" class="tl-tooltip tve-prevent-click tve-btn tve-btn-icon tve-asset-file-delete" data-id="<#= ID #>"><span class="tve-icon-trash-o"></span></a></span>