<td><#= test.get('title') #></td>
<td><#= test.get('type').join(' v ') #></td>
<td><#= test.get('notes') #></td>
<td><#= test.get('date_started') #></td>
<td class="tve-row-actions collapse-table-part-action">
    <a class="tve-btn  tve-btn-link tve-form-type-test tve-btn-link-icon-purple" href="#test/<#= test.id #>"><span class="tve-icon-view"></span><?php echo __('View Test', 'thrive-leads') ?></a>
</td>