<table>
    <thead>
    <tr>
        <th><?php echo __('Source', 'thrive-leads'); ?></th>
        <th><?php echo __('Type', 'thrive-leads'); ?></th>
        <th class="tve-table-sortable" data-order-by="impressions"><?php echo __('Impressions', 'thrive-leads'); ?></th>
        <th class="tve-table-sortable" data-order-by="conversions"><?php echo __('Conversions', 'thrive-leads'); ?></th>
        <th class="tve-table-sortable" data-order-by="conversion_rate"><?php echo __('Conversion Rate', 'thrive-leads'); ?></th>
        <th class="tve-table-sortable" data-order-by="leads"><?php echo __('New Leads', 'thrive-leads'); ?></th>
    </tr>
    </thead>
    <tbody id="tve-table-items"></tbody>
</table>