<div class="tve-total-new-leads">
	<div>
		<span class="tve-leads-count-title"><?php echo __('Average Conversion Rate', 'thrive-leads') ?></span>
		<span class="tve-leads-number"><#= average_rate #>%</span>
	</div>
</div>

<table class="tve-report-table">
	<thead>
		<tr>
			<th><?php echo __('Date', 'thrive-leads'); ?></th>
			<th><?php echo __('Rate', 'thrive-leads'); ?></th>
		</tr>
	</thead>
	<tbody id="tve-table-items"></tbody>
</table>