<table>
    <thead>
    <tr>
        <th><?php echo __('Contact', 'thrive-leads'); ?></th>
        <th><?php echo __('Date and time', 'thrive-leads'); ?></th>
        <th><?php echo __('Lead Group / Shortcode', 'thrive-leads'); ?></th>
        <th><?php echo __('Form type', 'thrive-leads'); ?></th>
        <th><?php echo __('Referrer URL', 'thrive-leads'); ?></th>
        <th><?php echo __('Form preview', 'thrive-leads'); ?></th>
    </tr>
    </thead>
    <tbody id="tve-table-items"></tbody>
</table>